baseurl = "http://hpcloud-mon.github.io/public"
languageCode = "en-us"
title = "Monasca"
theme = "material-design"

[params]
  description = "Monitoring-as-a-Service (at-Scale)"
  author = "Dr. Monasca"
